# Generated by Django 4.2 on 2023-05-25 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='audience_rating',
            field=models.FloatField(),
        ),
        migrations.AddField(
            model_name='movie',
            name='critic_rating',
            field=models.FloatField(),
        ),
        migrations.AddField(
            model_name='movie',
            name='imdbid',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='movie',
            name='img_url',
            field=models.URLField(default='N/A', max_length=600),
        ),
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_review', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userview.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
