# Generated by Django 4.2 on 2023-05-28 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userview', '0004_remove_movie_audience_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='movie',
            new_name='movie_id',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='value',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='user',
            new_name='user_id',
        ),
    ]
