# Generated by Django 4.2 on 2023-05-28 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userview', '0006_rename_movie_id_rating_movie_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user_review',
            new_name='comment',
        ),
    ]
